# Generated by Django 4.2.6 on 2023-10-16 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_checktest_test_pass_percentage_alter_question_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 18, 11, 56, 54, 559369, tzinfo=datetime.timezone.utc), verbose_name='tugatish sanasi'),
        ),
    ]
