# Generated by Django 4.2.6 on 2023-10-20 14:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_test_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checktest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checktests', to='main.test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 14, 38, 41, 870348, tzinfo=datetime.timezone.utc), verbose_name='tugatish sanasi'),
        ),
    ]
