# Generated by Django 3.2 on 2023-10-20 16:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_checktest_test_alter_test_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 16, 32, 5, 990490, tzinfo=utc), verbose_name='tugatish sanasi'),
        ),
    ]
