# Generated by Django 3.2 on 2023-10-21 09:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_test_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 9, 3, 41, 569047, tzinfo=utc), verbose_name='tugatish sanasi'),
        ),
    ]
