# Generated by Django 3.2 on 2023-10-24 17:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20231024_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 17, 38, 2, 546034, tzinfo=utc), verbose_name='tugatish sanasi'),
        ),
    ]
